### ISSUE TITLE
Conversion of string to date bug

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/panel_ops#67]
```
Traceback (most recent call last):
  File "main.py", line 294, in <module>
    main(**args)
  File "main.py", line 257, in main
    ops.mod_db.import_panel_form_data(param["new_panel"])
  File "/home/kimy/NHS/Panelapp/panel_ops/ops/mod_db.py", line 211, in import_panel_form_data
    data, add_on = parse_panel_form(panel_form)
  File "/home/kimy/NHS/Panelapp/panel_ops/ops/utils.py", line 1296, in parse_panel_form
    ci_version = metadata_df.iat[9, 1].strftime("%Y-%m-%d")
AttributeError: 'str' object has no attribute 'strftime
```

**Comment by Yu-jinKim** [comment]
Didn't get closed when merged. Weird
